Criada tela 017, solicito uma observação.
Itatech-Jr/Modern-School-UI pull request #16
Opened 2022-12-11 15:20 UTC by K4U4dev

2022-12-13 03:59 UTC, Ericles-Porty requested changes
- Remover navbar e utilizar menu hamburger
- Centralizar logo e nome
- Inserir menu hamburger na esquerda do header

2022-12-15 02:23 UTC, joannestephany reviewed
Alteração aprovada, porém esqueceu de apagar a tela antiga
@K4U4dev

2022-12-15 12:07 UTC, Ericles-Porty reviewed
Está enviando 2 arquivos iguais com a primeira letra diferente

2022-12-15 21:33 UTC, WalterHenri approved these changes
bom,  lançou a braba.

2022-12-15 22:17 UTC, Ericles-Porty approved these changes

2022-12-15 22:17 UTC, merged