commitzinho da tela 010
Itatech-Jr/Modern-School-UI pull request #55
Opened 2022-12-23 23:53 UTC by WalterHenri

aceite ai va.

2022-12-26 20:43 UTC, Gabrielx47 requested changes
O títtulo "Data"  poderia está ALINHADO A ESQUERDA, acredito que ficaria mais coerente.

2022-12-28 13:15 UTC, Gabrielx47 approved these changes
Bom trabalho, o alinhamento ao centro ficou perfeito.

2022-12-30 22:56 UTC, joannestephany approved these changes
Aprovado

2022-12-30 22:56 UTC, joannestephany commented
Na real na real, aprovei mas o símbolo da samu em azul ainda me deixa em dúvida

2022-12-30 22:56 UTC, merged